import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'pt' | 'ru' | 'hi' | 'zh' | 'fr' | 'ar';

export interface LanguageOption {
  code: Language;
  name: string;
  nativeName: string;
  flag: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇧🇷' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'zh', name: 'Mandarin', nativeName: '普通话', flag: '🇨🇳' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
];

const translations: Record<Language, Record<string, string>> = {
  en: {
    welcome: 'Welcome to BIFA',
    dashboard: 'Dashboard',
    myTeam: 'My Team',
    squad: 'Squad',
    transfers: 'Transfers',
    governance: 'Governance Portal',
    uploadDocument: 'Upload Document',
    competitions: 'Competitions',
    competitionEntries: 'Competition Entries',
    scheduleMatches: 'Schedule Matches',
    matchResults: 'Match Results',
    refereeRegistry: 'Referee Registry',
    myAssignments: 'My Assignments',
    matchReports: 'Match Reports',
    suspensions: 'Suspensions',
    referees: 'Referee Registry',
    players: 'Athlete Management',
    teams: 'Teams',
    disciplinary: 'Disciplinary',
    issueSanctions: 'Issue Sanctions',
    athletes: 'Athletes',
    statistics: 'Statistics',
    matchAssignment: 'Match Assignment',
    federations: 'Federations',
    userManagement: 'User Management',
    auditLogs: 'Audit Logs',
    changePassword: 'Change Password',
    stats: 'Statistics',
    secretariat: 'Match Assignment',
    logout: 'Logout',
    login: 'Sign In',
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    submit: 'Submit',
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    upload: 'Upload',
    approve: 'Approve',
    reject: 'Reject',
    status: 'Status',
    date: 'Date',
    name: 'Name',
    role: 'Role',
    country: 'Country',
    email: 'Email',
    actions: 'Actions',
    federation: 'BRICS International Football Alliance',
    tagline: 'Uniting Football Across BRICS+ Nations',
    create: 'Create',
    edit: 'Edit',
    delete: 'Delete',
    view: 'View',
    details: 'Details',
    add: 'Add',
    update: 'Update',
    close: 'Close',
    confirm: 'Confirm',
    success: 'Success',
    error: 'Error',
    warning: 'Warning',
    info: 'Information',
    news: 'News',
    memberNations: 'Member Nations',
    registeredPlayers: 'Registered Players',
    licensedReferees: 'Licensed Referees',
    activeCompetitions: 'Active Competitions',
    accessPlatform: 'Access Platform',
    systemArchitecture: 'System Architecture',
    matchCentre: 'Match Centre',
    platformModules: 'Platform Modules',
    modularScalable: 'Modular, scalable, RBAC-protected federation management',
    latestNews: 'Latest News',
    registerReferee: 'Register Referee',
    welcomeBack: 'Welcome back',
    systemOnline: 'System Online',
    liveMatch: 'Live Match',
    liveMatches: 'Live Matches',
    activeCompetitionsLabel: 'Active Competitions',
    registeredPlayersLabel: 'Registered Players',
    licensedRefereesLabel: 'Licensed Referees',
    openDisciplinary: 'Open Disciplinary',
    memberNationsLabel: 'Member Nations',
    pendingTasks: 'Pending Tasks',
    thisMonth: 'this month',
    thisSeason: 'this season',
    fifaGrade: 'FIFA grade',
    critical: 'critical',
    applicationsPending: 'applications pending',
    urgent: 'urgent',
    documentsCompliance: 'Documents & compliance',
    leaguesMatches: 'Leagues & matches',
    playerRegistry: 'Player registry',
    standingsStats: 'Standings & stats',
    tasksWorkflows: 'Tasks & workflows',
    officialRegistry: 'Official registry',
    suspensionReports: 'Suspension reports',
    casesSanctions: 'Cases & sanctions',
    myAssignedMatches: 'My Assigned Matches',
    matchSchedule: 'Match Schedule',
    viewAll: 'View all',
    noMatchesAssigned: 'No matches assigned to you yet',
    liveNow: 'Live Now',
    quickAccess: 'Quick Access',
    auditLog: 'Audit Log',
    bifaChampionsCup: 'BIFA Champions Cup',
    standings: 'Standings',
    fullTable: 'Full table',
    yourTime: 'Your time',
    athletes: 'Athletes',
  },
  pt: {
    welcome: 'Bem-vindo à BIFA',
    dashboard: 'Painel',
    myTeam: 'Minha Equipe',
    squad: 'Elenco',
    transfers: 'Transferências',
    governance: 'Portal de Governança',
    uploadDocument: 'Enviar Documento',
    competitions: 'Competições',
    competitionEntries: 'Inscrições de Competição',
    scheduleMatches: 'Agendar Partidas',
    matchResults: 'Resultados de Partidas',
    refereeRegistry: 'Registro de Árbitros',
    myAssignments: 'Minhas Atribuições',
    matchReports: 'Relatórios de Partidas',
    suspensions: 'Suspensões',
    referees: 'Registro de Árbitros',
    players: 'Gestão de Atletas',
    teams: 'Equipes',
    disciplinary: 'Disciplinar',
    issueSanctions: 'Emitir Sanções',
    athletes: 'Atletas',
    statistics: 'Estatísticas',
    matchAssignment: 'Atribuição de Partidas',
    federations: 'Federações',
    userManagement: 'Gestão de Usuários',
    auditLogs: 'Registros de Auditoria',
    changePassword: 'Alterar Senha',
    stats: 'Estatísticas',
    secretariat: 'Atribuição de Partidas',
    logout: 'Sair',
    login: 'Entrar',
    loading: 'Carregando...',
    save: 'Salvar',
    cancel: 'Cancelar',
    submit: 'Enviar',
    search: 'Pesquisar',
    filter: 'Filtrar',
    export: 'Exportar',
    upload: 'Enviar Arquivo',
    approve: 'Aprovar',
    reject: 'Rejeitar',
    status: 'Status',
    date: 'Data',
    name: 'Nome',
    role: 'Papel',
    country: 'País',
    email: 'E-mail',
    actions: 'Ações',
    federation: 'Aliança Internacional de Futebol BRICS',
    tagline: 'Unindo o Futebol nas Nações BRICS+',
    create: 'Criar',
    edit: 'Editar',
    delete: 'Excluir',
    view: 'Ver',
    details: 'Detalhes',
    add: 'Adicionar',
    update: 'Atualizar',
    close: 'Fechar',
    confirm: 'Confirmar',
    success: 'Sucesso',
    error: 'Erro',
    warning: 'Aviso',
    info: 'Informação',
    news: 'Notícias',
    memberNations: 'Nações Membros',
    registeredPlayers: 'Jogadores Registrados',
    licensedReferees: 'Árbitros Licenciados',
    activeCompetitions: 'Competições Ativas',
    accessPlatform: 'Acessar Plataforma',
    systemArchitecture: 'Arquitetura do Sistema',
    matchCentre: 'Centro de Partidas',
    platformModules: 'Módulos da Plataforma',
    modularScalable: 'Gestão federativa modular, escalável e protegida por RBAC',
    latestNews: 'Últimas Notícias',
    registerReferee: 'Registrar Árbitro',
    welcomeBack: 'Bem-vindo de volta',
    systemOnline: 'Sistema Online',
    liveMatch: 'Partida Ao Vivo',
    liveMatches: 'Partidas Ao Vivo',
    activeCompetitionsLabel: 'Competições Ativas',
    registeredPlayersLabel: 'Jogadores Registrados',
    licensedRefereesLabel: 'Árbitros Licenciados',
    openDisciplinary: 'Disciplinar Aberto',
    memberNationsLabel: 'Nações Membros',
    pendingTasks: 'Tarefas Pendentes',
    thisMonth: 'este mês',
    thisSeason: 'esta temporada',
    fifaGrade: 'grau FIFA',
    critical: 'crítico',
    applicationsPending: 'aplicações pendentes',
    urgent: 'urgente',
    documentsCompliance: 'Documentos e conformidade',
    leaguesMatches: 'Ligas e partidas',
    playerRegistry: 'Registro de jogadores',
    standingsStats: 'Classificações e estatísticas',
    tasksWorkflows: 'Tarefas e fluxos de trabalho',
    officialRegistry: 'Registro oficial',
    suspensionReports: 'Relatórios de suspensão',
    casesSanctions: 'Casos e sanções',
    myAssignedMatches: 'Minhas Partidas Atribuídas',
    matchSchedule: 'Calendário de Partidas',
    viewAll: 'Ver tudo',
    noMatchesAssigned: 'Nenhuma partida atribuída a você ainda',
    liveNow: 'Ao Vivo Agora',
    quickAccess: 'Acesso Rápido',
    auditLog: 'Registro de Auditoria',
    bifaChampionsCup: 'Copa dos Campeões BIFA',
    standings: 'Classificações',
    fullTable: 'Tabela completa',
    yourTime: 'Seu horário',
    athletes: 'Atletas',
  },
  ru: {
    welcome: 'Добро пожаловать в BIFA',
    dashboard: 'Панель управления',
    myTeam: 'Моя Команда',
    squad: 'Состав',
    transfers: 'Трансферы',
    governance: 'Портал управления',
    uploadDocument: 'Загрузить Документ',
    competitions: 'Соревнования',
    competitionEntries: 'Заявки на Соревнования',
    scheduleMatches: 'Расписание Матчей',
    matchResults: 'Результаты Матчей',
    refereeRegistry: 'Реестр Судей',
    myAssignments: 'Мои Назначения',
    matchReports: 'Отчеты о Матчах',
    suspensions: 'Дисквалификации',
    referees: 'Реестр судей',
    players: 'Управление спортсменами',
    teams: 'Команды',
    disciplinary: 'Дисциплина',
    issueSanctions: 'Выдать Санкции',
    athletes: 'Спортсмены',
    statistics: 'Статистика',
    matchAssignment: 'Назначение Матчей',
    federations: 'Федерации',
    userManagement: 'Управление Пользователями',
    auditLogs: 'Журналы Аудита',
    changePassword: 'Изменить Пароль',
    stats: 'Статистика',
    secretariat: 'Назначение Матчей',
    logout: 'Выйти',
    login: 'Войти',
    loading: 'Загрузка...',
    save: 'Сохранить',
    cancel: 'Отмена',
    submit: 'Отправить',
    search: 'Поиск',
    filter: 'Фильтр',
    export: 'Экспорт',
    upload: 'Загрузить',
    approve: 'Одобрить',
    reject: 'Отклонить',
    status: 'Статус',
    date: 'Дата',
    name: 'Имя',
    role: 'Роль',
    country: 'Страна',
    email: 'Эл. почта',
    actions: 'Действия',
    federation: 'Международный футбольный альянс БРИКС',
    tagline: 'Объединяя футбол в странах БРИКС+',
    create: 'Создать',
    edit: 'Редактировать',
    delete: 'Удалить',
    view: 'Просмотр',
    details: 'Детали',
    add: 'Добавить',
    update: 'Обновить',
    close: 'Закрыть',
    confirm: 'Подтвердить',
    success: 'Успех',
    error: 'Ошибка',
    warning: 'Предупреждение',
    info: 'Информация',
    news: 'Новости',
    memberNations: 'Страны-члены',
    registeredPlayers: 'Зарегистрированные игроки',
    licensedReferees: 'Лицензированные судьи',
    activeCompetitions: 'Активные соревнования',
    accessPlatform: 'Доступ к платформе',
    systemArchitecture: 'Архитектура системы',
    matchCentre: 'Центр матчей',
    platformModules: 'Модули платформы',
    modularScalable: 'Модульное, масштабируемое управление федерацией',
    latestNews: 'Последние новости',
    registerReferee: 'Зарегистрировать судью',
    welcomeBack: 'С возвращением',
    systemOnline: 'Система Онлайн',
    liveMatch: 'Прямой Эфир',
    liveMatches: 'Прямые Эфиры',
    activeCompetitionsLabel: 'Активные Соревнования',
    registeredPlayersLabel: 'Зарегистрированные Игроки',
    licensedRefereesLabel: 'Лицензированные Судьи',
    openDisciplinary: 'Открытые Дисциплинарные',
    memberNationsLabel: 'Страны-Члены',
    pendingTasks: 'Ожидающие Задачи',
    thisMonth: 'в этом месяце',
    thisSeason: 'в этом сезоне',
    fifaGrade: 'класс ФИФА',
    critical: 'критический',
    applicationsPending: 'заявки на рассмотрении',
    urgent: 'срочно',
    documentsCompliance: 'Документы и соответствие',
    leaguesMatches: 'Лиги и матчи',
    playerRegistry: 'Реестр игроков',
    standingsStats: 'Турнирные таблицы и статистика',
    tasksWorkflows: 'Задачи и рабочие процессы',
    officialRegistry: 'Официальный реестр',
    suspensionReports: 'Отчеты о дисквалификациях',
    casesSanctions: 'Дела и санкции',
    myAssignedMatches: 'Мои Назначенные Матчи',
    matchSchedule: 'Расписание Матчей',
    viewAll: 'Посмотреть все',
    noMatchesAssigned: 'У вас пока нет назначенных матчей',
    liveNow: 'Прямой Эфир',
    quickAccess: 'Быстрый Доступ',
    auditLog: 'Журнал Аудита',
    bifaChampionsCup: 'Кубок Чемпионов BIFA',
    standings: 'Турнирная Таблица',
    fullTable: 'Полная таблица',
    yourTime: 'Ваше время',
    athletes: 'Спортсмены',
  },
  hi: {
    welcome: 'BIFA में आपका स्वागत है',
    dashboard: 'डैशबोर्ड',
    governance: 'शासन पोर्टल',
    competitions: 'प्रतियोगिताएं',
    referees: 'रेफरी रजिस्ट्री',
    players: 'खिलाड़ी प्रबंधन',
    teams: 'टीमें',
    disciplinary: 'अनुशासनात्मक',
    stats: 'आंकड़े',
    secretariat: 'मैच असाइनमेंट',
    logout: 'लॉग आउट',
    login: 'साइन इन',
    loading: 'लोड हो रहा है...',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    submit: 'जमा करें',
    search: 'खोजें',
    filter: 'फ़िल्टर',
    export: 'निर्यात',
    upload: 'अपलोड',
    approve: 'स्वीकृत',
    reject: 'अस्वीकृत',
    status: 'स्थिति',
    date: 'तारीख',
    name: 'नाम',
    role: 'भूमिका',
    country: 'देश',
    email: 'ईमेल',
    actions: 'क्रियाएं',
    federation: 'BRICS अंतर्राष्ट्रीय फुटबॉल गठबंधन',
    tagline: 'BRICS+ राष्ट्रों में फुटबॉल को एकजुट करना',
    create: 'बनाएं',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    view: 'देखें',
    details: 'विवरण',
    add: 'जोड़ें',
    update: 'अपडेट करें',
    close: 'बंद करें',
    confirm: 'पुष्टि करें',
    success: 'सफलता',
    error: 'त्रुटि',
    warning: 'चेतावनी',
    info: 'जानकारी',
    news: 'समाचार',
    memberNations: 'सदस्य राष्ट्र',
    registeredPlayers: 'पंजीकृत खिलाड़ी',
    licensedReferees: 'लाइसेंसशुदा रेफरी',
    activeCompetitions: 'सक्रिय प्रतियोगिताएं',
    accessPlatform: 'प्लेटफॉर्म एक्सेस करें',
    systemArchitecture: 'सिस्टम आर्किटेक्चर',
    matchCentre: 'मैच सेंटर',
    platformModules: 'प्लेटफॉर्म मॉड्यूल',
    modularScalable: 'मॉड्यूलर, स्केलेबल, RBAC-संरक्षित फेडरेशन प्रबंधन',
    latestNews: 'ताजा खबरें',
    registerReferee: 'रेफरी पंजीकृत करें',
    welcomeBack: 'वापसी पर स्वागत है',
    systemOnline: 'सिस्टम ऑनलाइन',
    liveMatch: 'लाइव मैच',
    liveMatches: 'लाइव मैच',
    activeCompetitionsLabel: 'सक्रिय प्रतियोगिताएं',
    registeredPlayersLabel: 'पंजीकृत खिलाड़ी',
    licensedRefereesLabel: 'लाइसेंसशुदा रेफरी',
    openDisciplinary: 'खुले अनुशासनात्मक',
    memberNationsLabel: 'सदस्य राष्ट्र',
    pendingTasks: 'लंबित कार्य',
    thisMonth: 'इस महीने',
    thisSeason: 'इस सीज़न',
    fifaGrade: 'फीफा ग्रेड',
    critical: 'गंभीर',
    applicationsPending: 'आवेदन लंबित',
    urgent: 'तत्काल',
    documentsCompliance: 'दस्तावेज़ और अनुपालन',
    leaguesMatches: 'लीग और मैच',
    playerRegistry: 'खिलाड़ी रजिस्ट्री',
    standingsStats: 'स्टैंडिंग और आंकड़े',
    tasksWorkflows: 'कार्य और वर्कफ़्लो',
    officialRegistry: 'आधिकारिक रजिस्ट्री',
    suspensionReports: 'निलंबन रिपोर्ट',
    casesSanctions: 'मामले और प्रतिबंध',
    myAssignedMatches: 'मेरे सौंपे गए मैच',
    matchSchedule: 'मैच शेड्यूल',
    viewAll: 'सभी देखें',
    noMatchesAssigned: 'अभी तक आपको कोई मैच नहीं सौंपा गया है',
    liveNow: 'अभी लाइव',
    quickAccess: 'त्वरित पहुंच',
    auditLog: 'ऑडिट लॉग',
    bifaChampionsCup: 'BIFA चैंपियंस कप',
    standings: 'स्टैंडिंग',
    fullTable: 'पूरी तालिका',
    yourTime: 'आपका समय',
    athletes: 'एथलीट',
  },
  zh: {
    welcome: '欢迎来到BIFA',
    dashboard: '仪表板',
    governance: '治理门户',
    competitions: '赛事',
    referees: '裁判注册',
    players: '运动员管理',
    teams: '球队',
    disciplinary: '纪律',
    stats: '统计',
    secretariat: '比赛分配',
    logout: '退出',
    login: '登录',
    loading: '加载中...',
    save: '保存',
    cancel: '取消',
    submit: '提交',
    search: '搜索',
    filter: '筛选',
    export: '导出',
    upload: '上传',
    approve: '批准',
    reject: '拒绝',
    status: '状态',
    date: '日期',
    name: '姓名',
    role: '角色',
    country: '国家',
    email: '电子邮件',
    actions: '操作',
    federation: '金砖国际足球联盟',
    tagline: '在金砖+国家统一足球',
    create: '创建',
    edit: '编辑',
    delete: '删除',
    view: '查看',
    details: '详情',
    add: '添加',
    update: '更新',
    close: '关闭',
    confirm: '确认',
    success: '成功',
    error: '错误',
    warning: '警告',
    info: '信息',
    news: '新闻',
    memberNations: '成员国',
    registeredPlayers: '注册球员',
    licensedReferees: '授权裁判',
    activeCompetitions: '活跃赛事',
    accessPlatform: '访问平台',
    systemArchitecture: '系统架构',
    matchCentre: '比赛中心',
    platformModules: '平台模块',
    modularScalable: '模块化、可扩展、RBAC保护的联盟管理',
    latestNews: '最新消息',
    registerReferee: '注册裁判',
    welcomeBack: '欢迎回来',
    systemOnline: '系统在线',
    liveMatch: '直播比赛',
    liveMatches: '直播比赛',
    activeCompetitionsLabel: '活跃赛事',
    registeredPlayersLabel: '注册球员',
    licensedRefereesLabel: '授权裁判',
    openDisciplinary: '未结纪律',
    memberNationsLabel: '成员国',
    pendingTasks: '待办任务',
    thisMonth: '本月',
    thisSeason: '本赛季',
    fifaGrade: '国际足联等级',
    critical: '紧急',
    applicationsPending: '申请待处理',
    urgent: '紧急',
    documentsCompliance: '文件和合规',
    leaguesMatches: '联赛和比赛',
    playerRegistry: '球员注册',
    standingsStats: '排名和统计',
    tasksWorkflows: '任务和工作流',
    officialRegistry: '官方注册',
    suspensionReports: '停赛报告',
    casesSanctions: '案件和制裁',
    myAssignedMatches: '我的指派比赛',
    matchSchedule: '比赛日程',
    viewAll: '查看全部',
    noMatchesAssigned: '您还没有被分配比赛',
    liveNow: '正在直播',
    quickAccess: '快速访问',
    auditLog: '审计日志',
    bifaChampionsCup: 'BIFA冠军杯',
    standings: '排名',
    fullTable: '完整表格',
    yourTime: '您的时间',
    athletes: '运动员',
  },
  fr: {
    welcome: 'Bienvenue à BIFA',
    dashboard: 'Tableau de bord',
    governance: 'Portail de Gouvernance',
    competitions: 'Compétitions',
    referees: 'Registre des Arbitres',
    players: 'Gestion des Athlètes',
    teams: 'Équipes',
    disciplinary: 'Disciplinaire',
    stats: 'Statistiques',
    secretariat: 'Attribution de Match',
    logout: 'Déconnexion',
    login: 'Connexion',
    loading: 'Chargement...',
    save: 'Enregistrer',
    cancel: 'Annuler',
    submit: 'Soumettre',
    search: 'Rechercher',
    filter: 'Filtrer',
    export: 'Exporter',
    upload: 'Télécharger',
    approve: 'Approuver',
    reject: 'Rejeter',
    status: 'Statut',
    date: 'Date',
    name: 'Nom',
    role: 'Rôle',
    country: 'Pays',
    email: 'Email',
    actions: 'Actions',
    federation: 'Alliance Internationale de Football BRICS',
    tagline: 'Unir le Football à travers les Nations BRICS+',
    create: 'Créer',
    edit: 'Modifier',
    delete: 'Supprimer',
    view: 'Voir',
    details: 'Détails',
    add: 'Ajouter',
    update: 'Mettre à jour',
    close: 'Fermer',
    confirm: 'Confirmer',
    success: 'Succès',
    error: 'Erreur',
    warning: 'Avertissement',
    info: 'Information',
    news: 'Actualités',
    memberNations: 'Nations Membres',
    registeredPlayers: 'Joueurs Enregistrés',
    licensedReferees: 'Arbitres Licenciés',
    activeCompetitions: 'Compétitions Actives',
    accessPlatform: 'Accéder à la Plateforme',
    systemArchitecture: 'Architecture du Système',
    matchCentre: 'Centre des Matchs',
    platformModules: 'Modules de la Plateforme',
    modularScalable: 'Gestion de fédération modulaire, évolutive et protégée par RBAC',
    latestNews: 'Dernières Actualités',
    registerReferee: 'Enregistrer un Arbitre',
    welcomeBack: 'Bon retour',
    systemOnline: 'Système en Ligne',
    liveMatch: 'Match en Direct',
    liveMatches: 'Matchs en Direct',
    activeCompetitionsLabel: 'Compétitions Actives',
    registeredPlayersLabel: 'Joueurs Enregistrés',
    licensedRefereesLabel: 'Arbitres Licenciés',
    openDisciplinary: 'Dossiers Disciplinaires Ouverts',
    memberNationsLabel: 'Nations Membres',
    pendingTasks: 'Tâches en Attente',
    thisMonth: 'ce mois-ci',
    thisSeason: 'cette saison',
    fifaGrade: 'grade FIFA',
    critical: 'critique',
    applicationsPending: 'candidatures en attente',
    urgent: 'urgent',
    documentsCompliance: 'Documents & conformité',
    leaguesMatches: 'Ligues & matchs',
    playerRegistry: 'Registre des joueurs',
    standingsStats: 'Classements & statistiques',
    tasksWorkflows: 'Tâches & flux de travail',
    officialRegistry: 'Registre officiel',
    suspensionReports: 'Rapports de suspension',
    casesSanctions: 'Cas & sanctions',
    myAssignedMatches: 'Mes Matchs Assignés',
    matchSchedule: 'Calendrier des Matchs',
    viewAll: 'Voir tout',
    noMatchesAssigned: 'Aucun match ne vous a encore été assigné',
    liveNow: 'En Direct',
    quickAccess: 'Accès Rapide',
    auditLog: 'Journal d\'Audit',
    bifaChampionsCup: 'Coupe des Champions BIFA',
    standings: 'Classements',
    fullTable: 'Tableau complet',
    yourTime: 'Votre heure',
    athletes: 'Athlètes',
  },
  ar: {
    welcome: 'مرحباً بكم في BIFA',
    dashboard: 'لوحة التحكم',
    governance: 'بوابة الحوكمة',
    competitions: 'المسابقات',
    referees: 'سجل الحكام',
    players: 'إدارة الرياضيين',
    teams: 'الفرق',
    disciplinary: 'التأديب',
    stats: 'الإحصائيات',
    secretariat: 'تعيين المباريات',
    logout: 'تسجيل الخروج',
    login: 'تسجيل الدخول',
    loading: 'جار التحميل...',
    save: 'حفظ',
    cancel: 'إلغاء',
    submit: 'إرسال',
    search: 'بحث',
    filter: 'تصفية',
    export: 'تصدير',
    upload: 'رفع',
    approve: 'موافقة',
    reject: 'رفض',
    status: 'الحالة',
    date: 'التاريخ',
    name: 'الاسم',
    role: 'الدور',
    country: 'الدولة',
    email: 'البريد الإلكتروني',
    actions: 'الإجراءات',
    federation: 'تحالف بريكس الدولي لكرة القدم',
    tagline: 'توحيد كرة القدم عبر دول بريكس+',
    create: 'إنشاء',
    edit: 'تعديل',
    delete: 'حذف',
    view: 'عرض',
    details: 'تفاصيل',
    add: 'إضافة',
    update: 'تحديث',
    close: 'إغلاق',
    confirm: 'تأكيد',
    success: 'نجاح',
    error: 'خطأ',
    warning: 'تحذير',
    info: 'معلومات',
    news: 'الأخبار',
    memberNations: 'الدول الأعضاء',
    registeredPlayers: 'اللاعبون المسجلون',
    licensedReferees: 'الحكام المرخصون',
    activeCompetitions: 'المسابقات النشطة',
    accessPlatform: 'الوصول إلى المنصة',
    systemArchitecture: 'هندسة النظام',
    matchCentre: 'مركز المباريات',
    platformModules: 'وحدات المنصة',
    modularScalable: 'إدارة اتحادية معيارية وقابلة للتطوير ومحمية بـ RBAC',
    latestNews: 'آخر الأخبار',
    registerReferee: 'تسجيل حكم',
    welcomeBack: 'مرحباً بعودتك',
    systemOnline: 'النظام متصل',
    liveMatch: 'مباراة مباشرة',
    liveMatches: 'مباريات مباشرة',
    activeCompetitionsLabel: 'المسابقات النشطة',
    registeredPlayersLabel: 'اللاعبون المسجلون',
    licensedRefereesLabel: 'الحكام المرخصون',
    openDisciplinary: 'قضايا تأديبية مفتوحة',
    memberNationsLabel: 'الدول الأعضاء',
    pendingTasks: 'مهام معلقة',
    thisMonth: 'هذا الشهر',
    thisSeason: 'هذا الموسم',
    fifaGrade: 'درجة الفيفا',
    critical: 'حرجة',
    applicationsPending: 'طلبات معلقة',
    urgent: 'عاجل',
    documentsCompliance: 'المستندات والامتثال',
    leaguesMatches: 'الدوريات والمباريات',
    playerRegistry: 'سجل اللاعبين',
    standingsStats: 'الترتيب والإحصائيات',
    tasksWorkflows: 'المهام وسير العمل',
    officialRegistry: 'السجل الرسمي',
    suspensionReports: 'تقارير الإيقاف',
    casesSanctions: 'القضايا والعقوبات',
    myAssignedMatches: 'مبارياتي المعينة',
    matchSchedule: 'جدول المباريات',
    viewAll: 'عرض الكل',
    noMatchesAssigned: 'لم يتم تعيين أي مباريات لك بعد',
    liveNow: 'مباشر الآن',
    quickAccess: 'وصول سريع',
    auditLog: 'سجل التدقيق',
    bifaChampionsCup: 'كأس أبطال BIFA',
    standings: 'الترتيب',
    fullTable: 'الجدول الكامل',
    yourTime: 'وقتك المحلي',
    athletes: 'الرياضيون',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  currentLang: LanguageOption;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  const currentLang = LANGUAGES.find(l => l.code === language) || LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, currentLang }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
